// Client communication > Announcement.
// One active announcement per placement (`is_active` unique per `placement`):
// at most one popup, one header, and one footer can run at the same time. Enforced in the UI.
export const ANNOUNCEMENT_PLACEMENTS = [
  { value: "popup", label: "Pop up", hint: "Centred modal on first visit" },
  { value: "header", label: "Header", hint: "Bar directly below the menu" },
  { value: "footer", label: "Footer", hint: "Sticky bar at the bottom" },
];

export const ANNOUNCEMENT_CONTENT_TYPES = [
  { value: "text", label: "Text" },
  { value: "image", label: "Image" },
];

export const ANNOUNCEMENT_AUDIENCES = [
  { value: "everyone", label: "Everyone" },
  { value: "guests", label: "Signed-out visitors" },
  { value: "students", label: "Students" },
  { value: "clients", label: "Consultancy clients" },
];

export const ANNOUNCEMENT_TONES = [
  { value: "navy", label: "Navy", bg: "var(--navy-700)", fg: "#FFFFFF" },
  { value: "orange", label: "Orange", bg: "var(--orange-500)", fg: "#FFFFFF" },
  { value: "light", label: "Light", bg: "var(--gray-100)", fg: "var(--navy-700)" },
];

export const ANNOUNCEMENTS = [
  {
    id: "AN-410",
    title: "September cohorts are open",
    placement: "header",
    content_type: "text",
    body: "<p>Registration for the September cohorts closes 30 August — evening and weekend schedules available.</p>",
    image_url: "",
    image_alt: "",
    tone: "navy",
    cta_label: "See courses",
    cta_url: "/courses",
    audience: "everyone",
    dismissible: true,
    is_active: true,
    starts_at: "2026-08-18 08:00",
    ends_at: "2026-08-30 23:59",
    impressions: 18420,
    clicks: 1284,
    dismissals: 3106,
    created_by: "Tobi Adeyemi",
    created_at: "2026-08-17 14:22",
    updated_at: "2026-08-18 07:55",
  },
  {
    id: "AN-409",
    title: "Free automation audit — August only",
    placement: "popup",
    content_type: "image",
    body: "",
    image_url: "",
    image_alt: "Free automation audit through August — book a 30 minute call",
    tone: "light",
    cta_label: "Book the audit",
    cta_url: "/contact?topic=automation-audit",
    audience: "guests",
    dismissible: true,
    is_active: false,
    starts_at: "2026-08-01 00:00",
    ends_at: "2026-08-31 23:59",
    impressions: 9840,
    clicks: 612,
    dismissals: 7412,
    created_by: "Sade Balogun",
    created_at: "2026-07-30 11:04",
    updated_at: "2026-08-16 09:31",
  },
  {
    id: "AN-408",
    title: "Planned maintenance Sunday 03:00–05:00",
    placement: "footer",
    content_type: "text",
    body: "<p>The portal may be briefly unavailable on Sunday between 03:00 and 05:00 WAT while we upgrade the automation engine.</p>",
    image_url: "",
    image_alt: "",
    tone: "orange",
    cta_label: "",
    cta_url: "",
    audience: "clients",
    dismissible: false,
    is_active: false,
    starts_at: "2026-08-22 09:00",
    ends_at: "2026-08-24 06:00",
    impressions: 2140,
    clicks: 0,
    dismissals: 0,
    created_by: "Sade Balogun",
    created_at: "2026-08-22 14:10",
    updated_at: "2026-08-22 14:10",
  },
  {
    id: "AN-407",
    title: "New client portal is live",
    placement: "popup",
    content_type: "text",
    body: "<p>Projects, automations, and training now share one login. Nothing was lost — your history came with you.</p><p>Take the two-minute tour if you want to see what moved.</p>",
    image_url: "",
    image_alt: "",
    tone: "navy",
    cta_label: "Take the tour",
    cta_url: "/portal/tour",
    audience: "clients",
    dismissible: true,
    is_active: false,
    starts_at: "2026-08-06 09:00",
    ends_at: "2026-08-13 23:59",
    impressions: 4120,
    clicks: 1806,
    dismissals: 2210,
    created_by: "Sade Balogun",
    created_at: "2026-08-05 16:40",
    updated_at: "2026-08-13 23:59",
  },
  {
    id: "AN-406",
    title: "Certificates now carry a verification link",
    placement: "header",
    content_type: "text",
    body: "<p>Every certificate issued from July onward includes a link your employer can use to verify it.</p>",
    image_url: "",
    image_alt: "",
    tone: "light",
    cta_label: "View certificates",
    cta_url: "/certificates",
    audience: "students",
    dismissible: true,
    is_active: false,
    starts_at: "2026-07-20 08:00",
    ends_at: "2026-08-05 23:59",
    impressions: 12260,
    clicks: 894,
    dismissals: 2044,
    created_by: "Tobi Adeyemi",
    created_at: "2026-07-19 10:15",
    updated_at: "2026-08-05 23:59",
  },
];
