// Submissions from the public website contact form. Column names match the
// `contact_form_submissions` table, mirroring the Claude Design source
// (BWIN Consultants admin panel/data/contact-forms.js). Replace with
// modules/communication/services once the contact-forms API exists.
export const CONTACT_INTERESTS = ["Skill development", "Consultancy", "Business automation", "Not sure yet"];

export const CONTACT_STATUSES = ["new", "in_progress", "responded", "closed", "spam"];

export const CONTACT_STATUS_LABELS = {
  new: "New",
  in_progress: "In progress",
  responded: "Responded",
  closed: "Closed",
  spam: "Spam",
};

export const CONTACT_STATUS_TONES = {
  new: "info",
  in_progress: "warning",
  responded: "success",
  closed: "neutral",
  spam: "error",
};

export const CONTACT_SUBMISSIONS = [
  {
    id: "CF-10428",
    full_name: "Amara Okafor",
    email: "amara.okafor@brightpathlogistics.com",
    phone: "+234 803 441 9027",
    interested_in: "Business automation",
    message:
      "We run a 40-vehicle delivery fleet and still track dispatch on spreadsheets. Looking for something that assigns routes and flags late deliveries automatically. Can we book a call next week?",
    status: "new",
    source_page: "/contact",
    assigned_to: null,
    internal_note: "",
    ip_address: "102.89.34.17",
    created_at: "2026-08-23 09:12",
    updated_at: "2026-08-23 09:12",
  },
  {
    id: "CF-10427",
    full_name: "Daniel Mensah",
    email: "d.mensah@mensahagro.co",
    phone: "+233 24 778 1160",
    interested_in: "Consultancy",
    message: "Our margins dropped two quarters in a row. I want an outside read on pricing and supplier terms before we restructure.",
    status: "in_progress",
    source_page: "/services/consultancy",
    assigned_to: "Priya Raman",
    internal_note: "Discovery call held 22 Aug. Sending scoping doc Monday.",
    ip_address: "154.160.7.221",
    created_at: "2026-08-22 16:40",
    updated_at: "2026-08-23 08:05",
  },
  {
    id: "CF-10426",
    full_name: "Lena Vasquez",
    email: "lena.v@northstarclinics.com",
    phone: "+1 415 220 8834",
    interested_in: "Skill development",
    message: "I need to upskill 12 front-desk staff on our new patient system. Do you run private cohorts, and can the training happen on weekends?",
    status: "responded",
    source_page: "/courses",
    assigned_to: "Tobi Adeyemi",
    internal_note: "Sent private cohort pricing + weekend schedule. Waiting on headcount confirmation.",
    ip_address: "73.42.118.6",
    created_at: "2026-08-22 11:03",
    updated_at: "2026-08-22 15:22",
  },
  {
    id: "CF-10425",
    full_name: "Rashid Al-Mansoori",
    email: "rashid@almansoorigroup.ae",
    phone: "+971 50 664 2119",
    interested_in: "Not sure yet",
    message: "Family business, three branches. I know something needs to change but I am not sure whether the problem is process or people. Where would you start?",
    status: "new",
    source_page: "/contact",
    assigned_to: null,
    internal_note: "",
    ip_address: "94.200.55.130",
    created_at: "2026-08-21 19:47",
    updated_at: "2026-08-21 19:47",
  },
  {
    id: "CF-10424",
    full_name: "Chidera Nwosu",
    email: "chidera.nwosu@gmail.com",
    phone: "+234 706 552 3381",
    interested_in: "Skill development",
    message: "Is the data analytics course self-paced? I work full time and can only study evenings.",
    status: "responded",
    source_page: "/courses/data-analytics",
    assigned_to: "Tobi Adeyemi",
    internal_note: "Sent syllabus and evening cohort dates.",
    ip_address: "197.210.44.92",
    created_at: "2026-08-21 08:26",
    updated_at: "2026-08-21 10:14",
  },
  {
    id: "CF-10423",
    full_name: "Marco Bellini",
    email: "m.bellini@belliniceramica.it",
    phone: "+39 335 812 4407",
    interested_in: "Business automation",
    message: "We take orders by WhatsApp and re-type them into our invoicing system. Roughly 60 orders a day. Can that be connected?",
    status: "in_progress",
    source_page: "/services/automation",
    assigned_to: "Sade Balogun",
    internal_note: "Needs WhatsApp Business API check before we quote.",
    ip_address: "151.44.203.18",
    created_at: "2026-08-20 14:55",
    updated_at: "2026-08-22 09:31",
  },
  {
    id: "CF-10422",
    full_name: "Grace Wanjiru",
    email: "grace@wanjiruproperties.ke",
    phone: "+254 722 908 145",
    interested_in: "Consultancy",
    message: "Looking for help writing an operations manual before we franchise. Budget approved for Q4.",
    status: "closed",
    source_page: "/contact",
    assigned_to: "Priya Raman",
    internal_note: "Signed — moved to project CS-2291.",
    ip_address: "105.160.12.77",
    created_at: "2026-08-19 12:09",
    updated_at: "2026-08-20 17:48",
  },
  {
    id: "CF-10421",
    full_name: "Best SEO Offer",
    email: "promo@rank-first-now.biz",
    phone: "+1 000 000 0000",
    interested_in: "Not sure yet",
    message: "Guaranteed first page ranking in 7 days, reply for pricing sheet.",
    status: "spam",
    source_page: "/contact",
    assigned_to: null,
    internal_note: "Marked spam — third submission from same domain.",
    ip_address: "45.133.1.204",
    created_at: "2026-08-19 03:31",
    updated_at: "2026-08-19 09:02",
  },
  {
    id: "CF-10420",
    full_name: "Ibrahim Salihu",
    email: "ibrahim.salihu@sahelfoods.ng",
    phone: "+234 811 447 2290",
    interested_in: "Business automation",
    message: "Stock counts never match what the system says. I want alerts when a branch reports a variance over 5%.",
    status: "new",
    source_page: "/services/automation",
    assigned_to: null,
    internal_note: "",
    ip_address: "41.58.230.11",
    created_at: "2026-08-18 10:18",
    updated_at: "2026-08-18 10:18",
  },
  {
    id: "CF-10419",
    full_name: "Elena Petrova",
    email: "e.petrova@nordictextile.se",
    phone: "+46 70 331 8842",
    interested_in: "Skill development",
    message: "Do you issue certificates our HR team can verify? We need proof of completion for internal records.",
    status: "closed",
    source_page: "/courses",
    assigned_to: "Tobi Adeyemi",
    internal_note: "Answered — verification portal link shared.",
    ip_address: "78.72.14.55",
    created_at: "2026-08-17 15:37",
    updated_at: "2026-08-18 08:44",
  },
  {
    id: "CF-10418",
    full_name: "Femi Adebayo",
    email: "femi@adebayolegal.com",
    phone: "+234 802 119 6674",
    interested_in: "Consultancy",
    message: "Six-partner law firm. We want a review of how matters are assigned and billed before we hire two more associates.",
    status: "responded",
    source_page: "/contact",
    assigned_to: "Priya Raman",
    internal_note: "Proposal sent 18 Aug, follow up if no reply by 25 Aug.",
    ip_address: "197.253.9.140",
    created_at: "2026-08-16 09:02",
    updated_at: "2026-08-18 11:26",
  },
  {
    id: "CF-10417",
    full_name: "Hannah Kim",
    email: "hannah.kim@seolimstudio.kr",
    phone: "+82 10 4477 2018",
    interested_in: "Not sure yet",
    message: "Small design studio, seven people. Mostly curious what you would recommend for a team our size.",
    status: "closed",
    source_page: "/contact",
    assigned_to: "Sade Balogun",
    internal_note: "Not ready to buy — added to newsletter.",
    ip_address: "175.223.8.61",
    created_at: "2026-08-15 13:44",
    updated_at: "2026-08-16 10:11",
  },
];

export const CONTACT_ASSIGNEES = ["Priya Raman", "Tobi Adeyemi", "Sade Balogun"];
