// Student/client support tickets. Column names match a `support_tickets` table,
// with nested arrays mocking `support_ticket_messages` and `support_ticket_attachments`
// for the detail view. In future all data will come from the database.

export const TICKET_CATEGORIES = ["Billing", "Technical", "Course access", "Certificate", "Account", "General"];

export const TICKET_PRIORITIES = ["low", "medium", "high", "urgent"];
export const TICKET_PRIORITY_LABELS = { low: "Low", medium: "Medium", high: "High", urgent: "Urgent" };
export const TICKET_PRIORITY_TONES = { low: "neutral", medium: "info", high: "warning", urgent: "error" };

export const TICKET_STATUSES = ["open", "in_progress", "on_hold", "resolved", "closed"];
export const TICKET_STATUS_LABELS = {
  open: "Open",
  in_progress: "In progress",
  on_hold: "On hold",
  resolved: "Resolved",
  closed: "Closed",
};
export const TICKET_STATUS_TONES = {
  open: "info",
  in_progress: "warning",
  on_hold: "neutral",
  resolved: "success",
  closed: "neutral",
};

export const TICKET_ASSIGNEES = ["Priya Raman", "Tobi Adeyemi", "Sade Balogun", "Kwame Osei"];

export const SUPPORT_TICKETS = [
  {
    id: "TCK-3182",
    ticket_no: "TCK-3182",
    subject: "Cannot access module 4 videos",
    category: "Course access",
    student_name: "Chidera Nwosu",
    student_email: "chidera.nwosu@gmail.com",
    description: "I finished module 3 quiz but module 4 still shows a lock icon. I tried refreshing and logging out.",
    priority: "high",
    status: "open",
    source: "web",
    assigned_to: "Tobi Adeyemi",
    is_escalated: false,
    escalation_reason: "",
    total_replies: 1,
    attachment_count: 1,
    satisfaction_rating: null,
    satisfaction_comment: "",
    first_response_at: "2026-08-23 10:05",
    resolved_at: "",
    last_reply_at: "2026-08-23 10:05",
    created_at: "2026-08-23 09:40",
    updated_at: "2026-08-23 10:05",
    messages: [
      { author: "Chidera Nwosu", is_internal_note: false, is_system_message: false, message: "I finished module 3 quiz but module 4 still shows a lock icon. I tried refreshing and logging out.", created_at: "2026-08-23 09:40" },
      { author: "Tobi Adeyemi", is_internal_note: true, is_system_message: false, message: "Checked enrollment record — quiz 3 attempt shows \"in review\", not \"passed\". Likely a grading sync delay.", created_at: "2026-08-23 09:58" },
      { author: "Tobi Adeyemi", is_internal_note: false, is_system_message: false, message: "Thanks for the patience — I can see your quiz 3 result is still finalizing on our end. Re-grading it now, module 4 should unlock within the hour.", created_at: "2026-08-23 10:05" },
    ],
    attachments: [{ file_name: "module4-lock-screenshot.png", file_size: "212 KB" }],
  },
  {
    id: "TCK-3181",
    ticket_no: "TCK-3181",
    subject: "Charged twice for the same course",
    category: "Billing",
    student_name: "Marco Bellini",
    student_email: "m.bellini@belliniceramica.it",
    description: "My card statement shows two charges of $149 on the same day for the Automation Foundations course. Please refund the duplicate.",
    priority: "urgent",
    status: "in_progress",
    source: "email",
    assigned_to: "Sade Balogun",
    is_escalated: true,
    escalation_reason: "Payment dispute, needs finance sign-off before refund.",
    total_replies: 2,
    attachment_count: 1,
    satisfaction_rating: null,
    satisfaction_comment: "",
    first_response_at: "2026-08-22 15:10",
    resolved_at: "",
    last_reply_at: "2026-08-23 08:20",
    created_at: "2026-08-22 14:50",
    updated_at: "2026-08-23 08:20",
    messages: [
      { author: "Marco Bellini", is_internal_note: false, is_system_message: false, message: "My card statement shows two charges of $149 on the same day for the Automation Foundations course. Please refund the duplicate.", created_at: "2026-08-22 14:50" },
      { author: "Sade Balogun", is_internal_note: false, is_system_message: false, message: "Sorry about that, Marco — I can see both charges on our side too. Escalating to finance for a refund on the duplicate.", created_at: "2026-08-22 15:10" },
      { author: "Sade Balogun", is_internal_note: true, is_system_message: false, message: "Confirmed duplicate charge from a webhook retry. Refund request TCK-3181-R submitted to Stripe, pending finance approval.", created_at: "2026-08-23 08:20" },
    ],
    attachments: [{ file_name: "bank-statement.pdf", file_size: "88 KB" }],
  },
  {
    id: "TCK-3180",
    ticket_no: "TCK-3180",
    subject: "Certificate has a typo in my name",
    category: "Certificate",
    student_name: "Elena Petrova",
    student_email: "e.petrova@nordictextile.se",
    description: "The completion certificate for the Data Analytics course spells my last name as \"Petova\" instead of \"Petrova\". Can this be corrected and reissued?",
    priority: "medium",
    status: "resolved",
    source: "web",
    assigned_to: "Tobi Adeyemi",
    is_escalated: false,
    escalation_reason: "",
    total_replies: 2,
    attachment_count: 0,
    satisfaction_rating: 5,
    satisfaction_comment: "Fixed within a day, great support.",
    first_response_at: "2026-08-18 09:15",
    resolved_at: "2026-08-18 11:40",
    last_reply_at: "2026-08-18 11:40",
    created_at: "2026-08-18 08:50",
    updated_at: "2026-08-18 11:40",
    messages: [
      { author: "Elena Petrova", is_internal_note: false, is_system_message: false, message: "The completion certificate spells my last name as \"Petova\" instead of \"Petrova\". Can this be corrected and reissued?", created_at: "2026-08-18 08:50" },
      { author: "Tobi Adeyemi", is_internal_note: false, is_system_message: false, message: "Apologies for that — corrected your profile name and regenerated the certificate. New PDF is on your dashboard now.", created_at: "2026-08-18 11:40" },
      { author: "System", is_internal_note: false, is_system_message: true, message: "Ticket marked as resolved.", created_at: "2026-08-18 11:40" },
    ],
    attachments: [],
  },
  {
    id: "TCK-3179",
    ticket_no: "TCK-3179",
    subject: "Cannot reset password — no email received",
    category: "Account",
    student_name: "Rashid Al-Mansoori",
    student_email: "rashid@almansoorigroup.ae",
    description: "I requested a password reset three times and never received an email, checked spam too.",
    priority: "medium",
    status: "open",
    source: "web",
    assigned_to: null,
    is_escalated: false,
    escalation_reason: "",
    total_replies: 0,
    attachment_count: 0,
    satisfaction_rating: null,
    satisfaction_comment: "",
    first_response_at: "",
    resolved_at: "",
    last_reply_at: "",
    created_at: "2026-08-23 07:22",
    updated_at: "2026-08-23 07:22",
    messages: [
      { author: "Rashid Al-Mansoori", is_internal_note: false, is_system_message: false, message: "I requested a password reset three times and never received an email, checked spam too.", created_at: "2026-08-23 07:22" },
    ],
    attachments: [],
  },
  {
    id: "TCK-3178",
    ticket_no: "TCK-3178",
    subject: "Consultant kept rescheduling our session",
    category: "General",
    student_name: "Femi Adebayo",
    student_email: "femi@adebayolegal.com",
    description: "Our scoping call has been moved twice this week. We need a firm date before Friday.",
    priority: "high",
    status: "on_hold",
    source: "phone",
    assigned_to: "Priya Raman",
    is_escalated: false,
    escalation_reason: "",
    total_replies: 1,
    attachment_count: 0,
    satisfaction_rating: null,
    satisfaction_comment: "",
    first_response_at: "2026-08-21 12:00",
    resolved_at: "",
    last_reply_at: "2026-08-21 12:00",
    created_at: "2026-08-21 10:30",
    updated_at: "2026-08-21 12:00",
    messages: [
      { author: "Femi Adebayo", is_internal_note: false, is_system_message: false, message: "Our scoping call has been moved twice this week. We need a firm date before Friday.", created_at: "2026-08-21 10:30" },
      { author: "Priya Raman", is_internal_note: false, is_system_message: false, message: "Really sorry for the back and forth — checking my calendar and confirming a slot within the hour.", created_at: "2026-08-21 12:00" },
    ],
    attachments: [],
  },
  {
    id: "TCK-3177",
    ticket_no: "TCK-3177",
    subject: "Automation webhook stopped firing",
    category: "Technical",
    student_name: "Ibrahim Salihu",
    student_email: "ibrahim.salihu@sahelfoods.ng",
    description: "The stock variance alert automation was working last week and now nothing comes through, even with a 20% variance test.",
    priority: "urgent",
    status: "in_progress",
    source: "web",
    assigned_to: "Kwame Osei",
    is_escalated: true,
    escalation_reason: "Client on paid automation plan, revenue-impacting outage.",
    total_replies: 3,
    attachment_count: 2,
    satisfaction_rating: null,
    satisfaction_comment: "",
    first_response_at: "2026-08-22 09:05",
    resolved_at: "",
    last_reply_at: "2026-08-23 07:50",
    created_at: "2026-08-22 08:40",
    updated_at: "2026-08-23 07:50",
    messages: [
      { author: "Ibrahim Salihu", is_internal_note: false, is_system_message: false, message: "The stock variance alert automation was working last week and now nothing comes through, even with a 20% variance test.", created_at: "2026-08-22 08:40" },
      { author: "Kwame Osei", is_internal_note: false, is_system_message: false, message: "On it — pulling the automation run logs now.", created_at: "2026-08-22 09:05" },
      { author: "Kwame Osei", is_internal_note: true, is_system_message: false, message: "Found it — their POS export changed a column header, our parser is silently failing. Needs a mapping fix, not a client-side issue.", created_at: "2026-08-22 16:20" },
      { author: "Kwame Osei", is_internal_note: false, is_system_message: false, message: "Found the cause: a recent update to your POS export changed a column name. Deploying a fix today, will confirm once alerts are flowing again.", created_at: "2026-08-23 07:50" },
    ],
    attachments: [
      { file_name: "automation-run-log.txt", file_size: "340 KB" },
      { file_name: "pos-export-sample.csv", file_size: "54 KB" },
    ],
  },
  {
    id: "TCK-3176",
    ticket_no: "TCK-3176",
    subject: "Refund for cancelled cohort",
    category: "Billing",
    student_name: "Lena Vasquez",
    student_email: "lena.v@northstarclinics.com",
    description: "The private cohort we paid for was cancelled due to low enrollment on your side. Requesting a full refund.",
    priority: "medium",
    status: "resolved",
    source: "email",
    assigned_to: "Sade Balogun",
    is_escalated: false,
    escalation_reason: "",
    total_replies: 2,
    attachment_count: 0,
    satisfaction_rating: 4,
    satisfaction_comment: "Refund processed quickly, appreciated the clear communication.",
    first_response_at: "2026-08-16 13:00",
    resolved_at: "2026-08-17 09:30",
    last_reply_at: "2026-08-17 09:30",
    created_at: "2026-08-16 11:45",
    updated_at: "2026-08-17 09:30",
    messages: [
      { author: "Lena Vasquez", is_internal_note: false, is_system_message: false, message: "The private cohort we paid for was cancelled due to low enrollment on your side. Requesting a full refund.", created_at: "2026-08-16 11:45" },
      { author: "Sade Balogun", is_internal_note: false, is_system_message: false, message: "Agreed, that is on us — processing a full refund today, expect it in 3-5 business days.", created_at: "2026-08-17 09:30" },
    ],
    attachments: [],
  },
  {
    id: "TCK-3175",
    ticket_no: "TCK-3175",
    subject: "Duplicate account created by mistake",
    category: "Account",
    student_name: "Hannah Kim",
    student_email: "hannah.kim@seolimstudio.kr",
    description: "I signed up twice with different emails by accident and now my course progress is split across both.",
    priority: "low",
    status: "closed",
    source: "web",
    assigned_to: "Tobi Adeyemi",
    is_escalated: false,
    escalation_reason: "",
    total_replies: 1,
    attachment_count: 0,
    satisfaction_rating: 5,
    satisfaction_comment: "",
    first_response_at: "2026-08-14 10:20",
    resolved_at: "2026-08-14 10:20",
    last_reply_at: "2026-08-14 10:20",
    created_at: "2026-08-14 09:55",
    updated_at: "2026-08-14 10:20",
    messages: [
      { author: "Hannah Kim", is_internal_note: false, is_system_message: false, message: "I signed up twice with different emails by accident and now my course progress is split across both.", created_at: "2026-08-14 09:55" },
      { author: "Tobi Adeyemi", is_internal_note: false, is_system_message: false, message: "Merged both accounts under your primary email — all progress is combined now.", created_at: "2026-08-14 10:20" },
    ],
    attachments: [],
  },
];
