// public.automations (⋈ automation_categories for label joins). Column names
// match the DB schema exactly, mirroring the Claude Design source (BWIN
// Consultants admin panel/data/automations.js). Replace with
// modules/business/services once the automations API exists.

export const AUTOMATION_CATEGORIES = [
  { id: "acat-001", name: "Sales & CRM" },
  { id: "acat-002", name: "Finance & invoicing" },
  { id: "acat-003", name: "Operations" },
  { id: "acat-004", name: "Marketing" },
  { id: "acat-005", name: "People & onboarding" },
];

export const AUTOMATION_STATUSES = ["draft", "review", "published", "archived"];
export const AUTOMATION_STATUS_TONES = { draft: "neutral", review: "warning", published: "success", archived: "neutral" };

export const AUTOMATIONS = [
  {
    id: "b7c10001-3333-4a1b-9c2d-5e6f70830001",
    title: "Quote to invoice handoff",
    slug: "quote-to-invoice-handoff",
    description: "<p>When a quote is marked accepted, the invoice is raised, sent, and logged against the deal — no one retypes anything.</p>",
    lists: ["Accepted quote triggers the invoice", "Payment terms pulled from the client record", "Deal and accounting stay in sync"],
    category_id: "acat-002",
    image_url: "uploads/automation-invoice.png",
    video_url: "https://youtu.be/bwin-auto-invoice",
    status: "published",
    published_at: "2026-06-18 09:30:00+06",
    created_by: "Liam Chen",
    updated_by: "Sarah Whitmore",
    meta_title: "Quote to invoice automation | BWIN Consultants",
    meta_description: "Stop retyping accepted quotes into your accounting system.",
    meta_keywords: "invoicing automation, quotes, accounting",
    canonical_url: "https://bwin.com/automations/quote-to-invoice-handoff",
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-05-20 11:00:00+06",
    updated_at: "2026-08-11 15:20:00+06",
    deleted_at: null,
    runs_30d: 1840,
  },
  {
    id: "b7c10002-3333-4a1b-9c2d-5e6f70830002",
    title: "New lead routing",
    slug: "new-lead-routing",
    description: "<p>Every form submission is scored, assigned to the right owner, and chased if nobody replies within four hours.</p>",
    lists: ["Scored on company size and service interest", "Round-robin assignment by territory", "Escalation after four quiet hours"],
    category_id: "acat-001",
    image_url: null,
    video_url: null,
    status: "published",
    published_at: "2026-04-02 08:15:00+06",
    created_by: "Sarah Whitmore",
    updated_by: "Sarah Whitmore",
    meta_title: "Lead routing automation | BWIN Consultants",
    meta_description: "Route and chase every inbound lead without a spreadsheet.",
    meta_keywords: "lead routing, crm automation",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-03-11 10:40:00+06",
    updated_at: "2026-08-20 12:05:00+06",
    deleted_at: null,
    runs_30d: 612,
  },
  {
    id: "b7c10003-3333-4a1b-9c2d-5e6f70830003",
    title: "Weekly ops digest",
    slug: "weekly-ops-digest",
    description: "<p>Every Monday at 7am your team gets one email: last week's numbers, anything overdue, and what needs a decision this week.</p>",
    lists: ["Pulls from your project and finance tools", "One email, no dashboard login", "Overdue items called out first"],
    category_id: "acat-003",
    image_url: null,
    video_url: null,
    status: "published",
    published_at: "2026-02-09 07:00:00+06",
    created_by: "Amara Okafor",
    updated_by: "Liam Chen",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-01-28 09:00:00+06",
    updated_at: "2026-07-30 09:45:00+06",
    deleted_at: null,
    runs_30d: 4,
  },
  {
    id: "b7c10004-3333-4a1b-9c2d-5e6f70830004",
    title: "Client onboarding checklist",
    slug: "client-onboarding-checklist",
    description: "<p>A signed contract creates the project, the folder, the kickoff invite and the welcome email — in that order, every time.</p>",
    lists: ["Triggered by e-signature completion", "Creates project, folder and calendar invite", "Welcome email with the right owner's name"],
    category_id: "acat-005",
    image_url: null,
    video_url: null,
    status: "review",
    published_at: null,
    created_by: "Priya Nair",
    updated_by: "Priya Nair",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "noindex, nofollow",
    created_at: "2026-08-06 13:25:00+06",
    updated_at: "2026-08-22 10:30:00+06",
    deleted_at: null,
    runs_30d: 0,
  },
  {
    id: "b7c10005-3333-4a1b-9c2d-5e6f70830005",
    title: "Overdue invoice reminders",
    slug: "overdue-invoice-reminders",
    description: "<p>Polite, escalating reminders on day 3, 10 and 21 — paused automatically the moment payment lands.</p>",
    lists: ["Three-step reminder ladder", "Stops on payment", "Owner notified before the final notice"],
    category_id: "acat-002",
    image_url: null,
    video_url: null,
    status: "published",
    published_at: "2025-11-14 10:00:00+06",
    created_by: "Diego Fernandez",
    updated_by: "Diego Fernandez",
    meta_title: "Overdue invoice reminder automation | BWIN Consultants",
    meta_description: "Chase late payments without the awkward manual follow-up.",
    meta_keywords: "invoice reminders, receivables",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2025-10-30 14:10:00+06",
    updated_at: "2026-06-24 11:15:00+06",
    deleted_at: null,
    runs_30d: 236,
  },
  {
    id: "b7c10006-3333-4a1b-9c2d-5e6f70830006",
    title: "Campaign report roll-up",
    slug: "campaign-report-rollup",
    description: "<p>Pulls spend and results from each channel into one monthly sheet your marketing lead can actually read.</p>",
    lists: ["One sheet per month", "Spend, leads and cost per lead by channel"],
    category_id: "acat-004",
    image_url: null,
    video_url: null,
    status: "draft",
    published_at: null,
    created_by: "Liam Chen",
    updated_by: "Liam Chen",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "noindex, nofollow",
    created_at: "2026-08-15 16:00:00+06",
    updated_at: "2026-08-21 17:10:00+06",
    deleted_at: null,
    runs_30d: 0,
  },
  {
    id: "b7c10007-3333-4a1b-9c2d-5e6f70830007",
    title: "Legacy timesheet sync",
    slug: "legacy-timesheet-sync",
    description: "<p>Retired — replaced when the new time tracking tool went live.</p>",
    lists: [],
    category_id: "acat-003",
    image_url: null,
    video_url: null,
    status: "archived",
    published_at: "2025-05-02 09:00:00+06",
    created_by: "Amara Okafor",
    updated_by: "Amara Okafor",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "noindex, nofollow",
    created_at: "2025-04-18 09:00:00+06",
    updated_at: "2026-03-01 08:00:00+06",
    deleted_at: "2026-03-01 08:00:00+06",
    runs_30d: 0,
  },
];

export const nameById = (list, id) => (list.find((x) => x.id === id) || {}).name || "—";
