// public.consultancies (⋈ consultancy_categories for label joins). Column
// names match the DB schema exactly, mirroring the Claude Design source
// (BWIN Consultants admin panel/data/consultancies.js). Replace with
// modules/business/services once the consultancies API exists.

export const CONSULTANCY_CATEGORIES = [
  { id: "ccat-001", name: "Business strategy" },
  { id: "ccat-002", name: "Process & operations" },
  { id: "ccat-003", name: "Finance & compliance" },
  { id: "ccat-004", name: "People & HR" },
  { id: "ccat-005", name: "Technology" },
];

export const CONSULTANCY_TYPES = ["general", "retainer", "project", "advisory", "audit", "training"];
export const CONSULTANCY_STATUSES = ["active", "inactive", "draft", "archived"];
export const CONSULTANCY_STATUS_TONES = { active: "success", inactive: "neutral", draft: "warning", archived: "neutral" };

export const CONSULTANCIES = [
  {
    id: "a1b20001-2222-4a1b-9c2d-5e6f70820001",
    consultancy_code: "BWIN-CS-STR-01",
    title: "Growth strategy sprint",
    slug: "growth-strategy-sprint",
    description:
      "<p>A four-week sprint that ends with one written plan your leadership team agrees on: where growth comes from next year, what you stop doing, and who owns each move.</p>",
    consultancy_type: "project",
    category_id: "ccat-001",
    thumbnail: "uploads/consultancy-strategy.png",
    promo_video_url: "https://youtu.be/bwin-cs-str-01",
    sort_order: 1,
    status: "active",
    created_by: "Amara Okafor",
    updated_by: "Amara Okafor",
    meta_title: "Growth strategy sprint | BWIN Consultants",
    meta_description: "Four weeks to a growth plan your leadership team actually agrees on.",
    meta_keywords: "growth strategy, planning, consultancy",
    canonical_url: "https://bwin.com/consultancy/growth-strategy-sprint",
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2025-11-04 10:00:00+06",
    updated_at: "2026-08-12 09:30:00+06",
    deleted_at: null,
    engagements: 23,
  },
  {
    id: "a1b20002-2222-4a1b-9c2d-5e6f70820002",
    consultancy_code: "BWIN-CS-OPS-04",
    title: "Operations health check",
    slug: "operations-health-check",
    description:
      "<p>We shadow your team for two weeks, map every handoff, and hand back a ranked list of the ten changes that would save the most hours.</p>",
    consultancy_type: "audit",
    category_id: "ccat-002",
    thumbnail: null,
    promo_video_url: null,
    sort_order: 2,
    status: "active",
    created_by: "Sarah Whitmore",
    updated_by: "Priya Nair",
    meta_title: "Operations health check | BWIN Consultants",
    meta_description: "A two-week audit of how work actually moves through your business.",
    meta_keywords: "operations audit, process mapping",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2025-12-18 14:20:00+06",
    updated_at: "2026-07-29 16:45:00+06",
    deleted_at: null,
    engagements: 41,
  },
  {
    id: "a1b20003-2222-4a1b-9c2d-5e6f70820003",
    consultancy_code: "BWIN-CS-FIN-02",
    title: "Monthly finance advisory",
    slug: "monthly-finance-advisory",
    description:
      "<p>A fixed monthly retainer: we close your books with your bookkeeper, review the numbers with you, and flag anything that needs a decision.</p>",
    consultancy_type: "retainer",
    category_id: "ccat-003",
    thumbnail: null,
    promo_video_url: null,
    sort_order: 3,
    status: "active",
    created_by: "Diego Fernandez",
    updated_by: "Diego Fernandez",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-01-22 11:05:00+06",
    updated_at: "2026-08-02 10:10:00+06",
    deleted_at: null,
    engagements: 12,
  },
  {
    id: "a1b20004-2222-4a1b-9c2d-5e6f70820004",
    consultancy_code: "BWIN-CS-HR-03",
    title: "Hiring process rebuild",
    slug: "hiring-process-rebuild",
    description:
      "<p>Rewrite your job ads, interview scorecards and offer process so hiring stops depending on who happens to run the interview.</p>",
    consultancy_type: "project",
    category_id: "ccat-004",
    thumbnail: null,
    promo_video_url: null,
    sort_order: 4,
    status: "draft",
    created_by: "Priya Nair",
    updated_by: "Priya Nair",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "noindex, nofollow",
    created_at: "2026-08-08 09:15:00+06",
    updated_at: "2026-08-21 13:40:00+06",
    deleted_at: null,
    engagements: 0,
  },
  {
    id: "a1b20005-2222-4a1b-9c2d-5e6f70820005",
    consultancy_code: "BWIN-CS-TEC-07",
    title: "Systems selection advisory",
    slug: "systems-selection-advisory",
    description:
      "<p>Independent help choosing your next CRM, ERP or ticketing system — requirements, shortlist, demos and a recommendation you can defend to the board.</p>",
    consultancy_type: "advisory",
    category_id: "ccat-005",
    thumbnail: null,
    promo_video_url: null,
    sort_order: 5,
    status: "active",
    created_by: "Liam Chen",
    updated_by: "Liam Chen",
    meta_title: "Systems selection advisory | BWIN Consultants",
    meta_description: "Vendor-neutral help picking the software your operations will live in.",
    meta_keywords: "crm selection, erp, software advisory",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-02-14 15:30:00+06",
    updated_at: "2026-08-19 11:20:00+06",
    deleted_at: null,
    engagements: 18,
  },
  {
    id: "a1b20006-2222-4a1b-9c2d-5e6f70820006",
    consultancy_code: "BWIN-CS-OPS-09",
    title: "Team automation workshop",
    slug: "team-automation-workshop",
    description: "<p>A one-day on-site workshop where your team leaves with two automations already running.</p>",
    consultancy_type: "training",
    category_id: "ccat-002",
    thumbnail: null,
    promo_video_url: null,
    sort_order: 6,
    status: "inactive",
    created_by: "Sarah Whitmore",
    updated_by: "Amara Okafor",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2025-09-30 08:45:00+06",
    updated_at: "2026-06-11 14:05:00+06",
    deleted_at: null,
    engagements: 7,
  },
  {
    id: "a1b20007-2222-4a1b-9c2d-5e6f70820007",
    consultancy_code: "BWIN-CS-GEN-05",
    title: "Discovery call follow-up pack",
    slug: "discovery-call-follow-up",
    description: "<p>Retired offering — replaced by the free discovery call.</p>",
    consultancy_type: "general",
    category_id: null,
    thumbnail: null,
    promo_video_url: null,
    sort_order: 7,
    status: "archived",
    created_by: "Amara Okafor",
    updated_by: "Amara Okafor",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "noindex, nofollow",
    created_at: "2025-06-02 10:00:00+06",
    updated_at: "2026-05-20 09:00:00+06",
    deleted_at: "2026-05-20 09:00:00+06",
    engagements: 3,
  },
];

export const nameById = (list, id) => (list.find((x) => x.id === id) || {}).name || "—";
