// public.courses (⋈ course_categories, course_types, delivery_modes for label
// joins). Column names match the DB schema exactly, mirroring the Claude
// Design source (BWIN Consultants admin panel/data/courses.js). Replace with
// modules/lms/services once the courses API exists.

export const COURSE_CATEGORIES = [
  { id: "cat-0001", name: "Business automation" },
  { id: "cat-0002", name: "Data & analytics" },
  { id: "cat-0003", name: "Leadership" },
  { id: "cat-0004", name: "Digital marketing" },
  { id: "cat-0005", name: "Finance & compliance" },
];

export const COURSE_TYPES = [
  { id: "typ-0001", name: "Certification" },
  { id: "typ-0002", name: "Short course" },
  { id: "typ-0003", name: "Workshop" },
  { id: "typ-0004", name: "Diploma" },
];

export const DELIVERY_MODES = [
  { id: "dlv-0001", name: "Self-paced" },
  { id: "dlv-0002", name: "Live online" },
  { id: "dlv-0003", name: "Blended" },
  { id: "dlv-0004", name: "In-person" },
];

export const COURSE_LEVELS = ["beginner", "intermediate", "advanced", "expert"];
export const COURSE_STATUSES = ["draft", "review", "published", "scheduled", "archived"];
export const COURSE_VISIBILITIES = ["public", "private", "unlisted", "password"];
export const COURSE_LANGUAGES = ["english", "bangla", "spanish"];

export const COURSE_STATUS_TONES = {
  draft: "neutral",
  review: "warning",
  published: "success",
  scheduled: "warning",
  archived: "neutral",
};
export const COURSE_LEVEL_TONES = {
  beginner: "success",
  intermediate: "neutral",
  advanced: "warning",
  expert: "error",
};

export const COURSES = [
  {
    id: "e5f60001-1111-4a1b-9c2d-5e6f70810001",
    course_code: "BWIN-AUT-101",
    title: "Workflow automation foundations",
    slug: "workflow-automation-foundations",
    short_description: "Map a manual process end to end, then automate the parts that cost you the most hours.",
    description: "A practical first course on identifying automation candidates inside an operations team…",
    learning_outcomes: ["Map any manual process", "Score tasks by automation ROI", "Ship a first working automation"],
    requirements: ["Access to your team's tooling", "No coding required"],
    target_audience: ["Operations managers", "Business owners"],
    category_id: "cat-0001",
    level: "beginner",
    language: "english",
    course_type: "typ-0002",
    delivery_mode: "dlv-0001",
    thumbnail: "uploads/course-automation.png",
    cover_image: null,
    promo_video_url: "https://youtu.be/bwin-aut-101",
    intro_video_url: null,
    duration_hours: 8,
    duration_minutes: 30,
    total_modules: 6,
    total_lessons: 34,
    total_quizzes: 6,
    total_assignments: 3,
    total_resources: 18,
    passing_score: 70,
    certificate_enabled: true,
    certificate_template_id: "tpl-0001",
    max_attempts: 3,
    seat_limit: null,
    price: 149.0,
    discount_price: 99.0,
    currency: "USD",
    enrollment_start_date: "2026-07-01 00:00:00+06",
    enrollment_end_date: "2026-12-31 23:59:00+06",
    course_start_date: "2026-07-15 00:00:00+06",
    course_end_date: null,
    status: "published",
    visibility: "public",
    featured: true,
    allow_reviews: true,
    allow_discussion: true,
    sort_order: 1,
    created_by: "Amara Okafor",
    updated_by: "Sarah Whitmore",
    published_at: "2026-07-10 09:12:00+06",
    meta_title: "Workflow automation foundations | BWIN",
    meta_description: "Learn to map and automate your manual operations work.",
    meta_keywords: "automation, workflow, operations",
    canonical_url: "https://bwin.com/courses/workflow-automation-foundations",
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-05-02 11:00:00+06",
    updated_at: "2026-08-18 14:22:00+06",
    deleted_at: null,
    enrolled: 412,
  },
  {
    id: "e5f60002-1111-4a1b-9c2d-5e6f70810002",
    course_code: "BWIN-AUT-210",
    title: "Building automations with no-code tools",
    slug: "no-code-automations",
    short_description: "Connect the tools you already pay for and let them do the handoffs.",
    description: "Hands-on build course covering triggers, branching, error handling and monitoring…",
    learning_outcomes: ["Design multi-step flows", "Handle failures safely", "Monitor running automations"],
    requirements: ["Completed BWIN-AUT-101"],
    target_audience: ["Ops leads", "Internal tooling owners"],
    category_id: "cat-0001",
    level: "intermediate",
    language: "english",
    course_type: "typ-0001",
    delivery_mode: "dlv-0003",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 16,
    duration_minutes: 0,
    total_modules: 9,
    total_lessons: 58,
    total_quizzes: 9,
    total_assignments: 6,
    total_resources: 27,
    passing_score: 75,
    certificate_enabled: true,
    certificate_template_id: "tpl-0001",
    max_attempts: 2,
    seat_limit: 40,
    price: 349.0,
    discount_price: null,
    currency: "USD",
    enrollment_start_date: "2026-08-01 00:00:00+06",
    enrollment_end_date: "2026-09-20 23:59:00+06",
    course_start_date: "2026-10-01 00:00:00+06",
    course_end_date: "2026-12-12 00:00:00+06",
    status: "published",
    visibility: "public",
    featured: true,
    allow_reviews: true,
    allow_discussion: true,
    sort_order: 2,
    created_by: "Sarah Whitmore",
    updated_by: "Sarah Whitmore",
    published_at: "2026-07-28 10:40:00+06",
    meta_title: "No-code automation certification | BWIN",
    meta_description: "Build, ship and monitor production automations without writing code.",
    meta_keywords: "no-code, zapier, make, automation",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-06-11 09:30:00+06",
    updated_at: "2026-08-21 16:05:00+06",
    deleted_at: null,
    enrolled: 188,
  },
  {
    id: "e5f60003-1111-4a1b-9c2d-5e6f70810003",
    course_code: "BWIN-DAT-140",
    title: "Dashboards that people actually read",
    slug: "dashboards-people-read",
    short_description: "Turn raw operational data into one screen your team checks every morning.",
    description: "Covers metric selection, chart choice, layout and review cadence…",
    learning_outcomes: ["Pick the right metric", "Choose honest charts", "Run a weekly metrics review"],
    requirements: ["Spreadsheet basics"],
    target_audience: ["Analysts", "Team leads"],
    category_id: "cat-0002",
    level: "beginner",
    language: "english",
    course_type: "typ-0002",
    delivery_mode: "dlv-0001",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 6,
    duration_minutes: 45,
    total_modules: 5,
    total_lessons: 22,
    total_quizzes: 4,
    total_assignments: 2,
    total_resources: 11,
    passing_score: 60,
    certificate_enabled: true,
    certificate_template_id: null,
    max_attempts: null,
    seat_limit: null,
    price: 89.0,
    discount_price: 59.0,
    currency: "USD",
    enrollment_start_date: "2026-06-01 00:00:00+06",
    enrollment_end_date: null,
    course_start_date: null,
    course_end_date: null,
    status: "published",
    visibility: "public",
    featured: false,
    allow_reviews: true,
    allow_discussion: false,
    sort_order: 3,
    created_by: "Liam Chen",
    updated_by: "Liam Chen",
    published_at: "2026-06-04 08:00:00+06",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-04-19 13:15:00+06",
    updated_at: "2026-08-02 11:47:00+06",
    deleted_at: null,
    enrolled: 305,
  },
  {
    id: "e5f60004-1111-4a1b-9c2d-5e6f70810004",
    course_code: "BWIN-LEA-320",
    title: "Leading an operations team through change",
    slug: "leading-through-change",
    short_description: "Keep a team steady while the processes underneath them get rebuilt.",
    description: "Live cohort course on change communication, resistance and adoption tracking…",
    learning_outcomes: ["Write a change narrative", "Handle resistance", "Track adoption honestly"],
    requirements: ["Two or more years managing people"],
    target_audience: ["Managers", "Department heads"],
    category_id: "cat-0003",
    level: "advanced",
    language: "english",
    course_type: "typ-0003",
    delivery_mode: "dlv-0002",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 12,
    duration_minutes: 0,
    total_modules: 4,
    total_lessons: 16,
    total_quizzes: 2,
    total_assignments: 4,
    total_resources: 9,
    passing_score: 70,
    certificate_enabled: true,
    certificate_template_id: "tpl-0002",
    max_attempts: 1,
    seat_limit: 24,
    price: 590.0,
    discount_price: null,
    currency: "USD",
    enrollment_start_date: "2026-09-01 00:00:00+06",
    enrollment_end_date: "2026-10-15 23:59:00+06",
    course_start_date: "2026-11-02 00:00:00+06",
    course_end_date: "2026-11-30 00:00:00+06",
    status: "scheduled",
    visibility: "public",
    featured: false,
    allow_reviews: true,
    allow_discussion: true,
    sort_order: 4,
    created_by: "Amara Okafor",
    updated_by: "Amara Okafor",
    published_at: null,
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-07-30 15:20:00+06",
    updated_at: "2026-08-22 09:03:00+06",
    deleted_at: null,
    enrolled: 0,
  },
  {
    id: "e5f60005-1111-4a1b-9c2d-5e6f70810005",
    course_code: "BWIN-MKT-115",
    title: "Local SEO for service businesses",
    slug: "local-seo-service-businesses",
    short_description: "Get found by the customers who are already searching for what you do.",
    description: "Practical SEO sequence for single-location and multi-location service firms…",
    learning_outcomes: ["Fix your listings", "Build service pages that rank", "Measure calls, not clicks"],
    requirements: ["A live website"],
    target_audience: ["Small business owners"],
    category_id: "cat-0004",
    level: "beginner",
    language: "bangla",
    course_type: "typ-0002",
    delivery_mode: "dlv-0001",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 5,
    duration_minutes: 20,
    total_modules: 4,
    total_lessons: 19,
    total_quizzes: 3,
    total_assignments: 1,
    total_resources: 7,
    passing_score: 60,
    certificate_enabled: false,
    certificate_template_id: null,
    max_attempts: null,
    seat_limit: null,
    price: 0.0,
    discount_price: null,
    currency: "USD",
    enrollment_start_date: null,
    enrollment_end_date: null,
    course_start_date: null,
    course_end_date: null,
    status: "review",
    visibility: "private",
    featured: false,
    allow_reviews: false,
    allow_discussion: true,
    sort_order: 5,
    created_by: "Liam Chen",
    updated_by: "Priya Nair",
    published_at: null,
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "noindex, nofollow",
    created_at: "2026-08-05 10:10:00+06",
    updated_at: "2026-08-20 17:35:00+06",
    deleted_at: null,
    enrolled: 0,
  },
  {
    id: "e5f60006-1111-4a1b-9c2d-5e6f70810006",
    course_code: "BWIN-FIN-260",
    title: "VAT and compliance basics for SMEs",
    slug: "vat-compliance-basics",
    short_description: "Stay compliant without hiring a full-time finance team.",
    description: "Walks through registration, filing cycles, record keeping and common audit findings…",
    learning_outcomes: ["Understand filing cycles", "Keep audit-ready records", "Avoid the five common penalties"],
    requirements: ["Bookkeeping access"],
    target_audience: ["Founders", "Finance officers"],
    category_id: "cat-0005",
    level: "intermediate",
    language: "bangla",
    course_type: "typ-0002",
    delivery_mode: "dlv-0002",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 9,
    duration_minutes: 15,
    total_modules: 7,
    total_lessons: 28,
    total_quizzes: 7,
    total_assignments: 2,
    total_resources: 15,
    passing_score: 80,
    certificate_enabled: true,
    certificate_template_id: "tpl-0001",
    max_attempts: 3,
    seat_limit: 60,
    price: 199.0,
    discount_price: 149.0,
    currency: "USD",
    enrollment_start_date: "2026-05-01 00:00:00+06",
    enrollment_end_date: "2026-08-01 23:59:00+06",
    course_start_date: "2026-05-20 00:00:00+06",
    course_end_date: "2026-07-25 00:00:00+06",
    status: "archived",
    visibility: "unlisted",
    featured: false,
    allow_reviews: true,
    allow_discussion: false,
    sort_order: 6,
    created_by: "Diego Fernandez",
    updated_by: "Diego Fernandez",
    published_at: "2026-04-28 12:00:00+06",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-03-14 09:45:00+06",
    updated_at: "2026-08-01 08:30:00+06",
    deleted_at: null,
    enrolled: 96,
  },
  {
    id: "e5f60007-1111-4a1b-9c2d-5e6f70810007",
    course_code: "BWIN-DAT-410",
    title: "Forecasting for operations planning",
    slug: "forecasting-operations-planning",
    short_description: "Plan headcount and inventory from your own history instead of guesswork.",
    description: "Expert-level course on baseline models, seasonality and forecast review…",
    learning_outcomes: ["Build a baseline forecast", "Adjust for seasonality", "Review forecast error monthly"],
    requirements: ["Comfortable with spreadsheets and basic statistics"],
    target_audience: ["Analysts", "Planners"],
    category_id: "cat-0002",
    level: "expert",
    language: "english",
    course_type: "typ-0004",
    delivery_mode: "dlv-0003",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 24,
    duration_minutes: 0,
    total_modules: 12,
    total_lessons: 72,
    total_quizzes: 12,
    total_assignments: 8,
    total_resources: 40,
    passing_score: 85,
    certificate_enabled: true,
    certificate_template_id: "tpl-0003",
    max_attempts: 2,
    seat_limit: 30,
    price: 890.0,
    discount_price: 790.0,
    currency: "USD",
    enrollment_start_date: "2026-08-10 00:00:00+06",
    enrollment_end_date: "2026-11-01 23:59:00+06",
    course_start_date: "2026-11-15 00:00:00+06",
    course_end_date: "2027-02-15 00:00:00+06",
    status: "draft",
    visibility: "private",
    featured: false,
    allow_reviews: true,
    allow_discussion: true,
    sort_order: 7,
    created_by: "Priya Nair",
    updated_by: "Priya Nair",
    published_at: null,
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "noindex, nofollow",
    created_at: "2026-08-12 14:00:00+06",
    updated_at: "2026-08-22 10:18:00+06",
    deleted_at: null,
    enrolled: 0,
  },
  {
    id: "e5f60008-1111-4a1b-9c2d-5e6f70810008",
    course_code: "BWIN-MKT-230",
    title: "Email that gets replies",
    slug: "email-that-gets-replies",
    short_description: "Write outreach and lifecycle email your customers answer.",
    description: "Copy workshop with live critique of participants' real sequences…",
    learning_outcomes: ["Write a plain-spoken sequence", "Segment without over-engineering", "Read reply data"],
    requirements: ["An email tool you can send from"],
    target_audience: ["Marketers", "Founders"],
    category_id: "cat-0004",
    level: "intermediate",
    language: "english",
    course_type: "typ-0003",
    delivery_mode: "dlv-0002",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 4,
    duration_minutes: 0,
    total_modules: 3,
    total_lessons: 12,
    total_quizzes: 1,
    total_assignments: 3,
    total_resources: 6,
    passing_score: 60,
    certificate_enabled: false,
    certificate_template_id: null,
    max_attempts: null,
    seat_limit: 20,
    price: 129.0,
    discount_price: null,
    currency: "USD",
    enrollment_start_date: "2026-08-15 00:00:00+06",
    enrollment_end_date: "2026-09-05 23:59:00+06",
    course_start_date: "2026-09-12 00:00:00+06",
    course_end_date: "2026-09-13 00:00:00+06",
    status: "published",
    visibility: "public",
    featured: false,
    allow_reviews: true,
    allow_discussion: true,
    sort_order: 8,
    created_by: "Sarah Whitmore",
    updated_by: "Sarah Whitmore",
    published_at: "2026-08-14 09:00:00+06",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-07-22 11:25:00+06",
    updated_at: "2026-08-19 13:41:00+06",
    deleted_at: null,
    enrolled: 17,
  },
  {
    id: "e5f60009-1111-4a1b-9c2d-5e6f70810009",
    course_code: "BWIN-AUT-050",
    title: "Automation glossary for busy owners",
    slug: "automation-glossary",
    short_description: "Twelve short lessons so you can follow the conversation with your vendors.",
    description: "A free primer on the vocabulary of automation projects…",
    learning_outcomes: ["Speak the vocabulary", "Ask vendors better questions"],
    requirements: [],
    target_audience: ["Business owners"],
    category_id: "cat-0001",
    level: "beginner",
    language: "english",
    course_type: "typ-0002",
    delivery_mode: "dlv-0001",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 1,
    duration_minutes: 40,
    total_modules: 2,
    total_lessons: 12,
    total_quizzes: 1,
    total_assignments: 0,
    total_resources: 3,
    passing_score: 0,
    certificate_enabled: false,
    certificate_template_id: null,
    max_attempts: null,
    seat_limit: null,
    price: 0.0,
    discount_price: null,
    currency: "USD",
    enrollment_start_date: null,
    enrollment_end_date: null,
    course_start_date: null,
    course_end_date: null,
    status: "published",
    visibility: "public",
    featured: false,
    allow_reviews: false,
    allow_discussion: false,
    sort_order: 9,
    created_by: "Liam Chen",
    updated_by: "Liam Chen",
    published_at: "2026-02-02 10:00:00+06",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "index, follow",
    created_at: "2026-01-18 09:00:00+06",
    updated_at: "2026-06-11 15:12:00+06",
    deleted_at: null,
    enrolled: 1204,
  },
  {
    id: "e5f60010-1111-4a1b-9c2d-5e6f70810010",
    course_code: "BWIN-LEA-150",
    title: "Delegation for first-time managers",
    slug: "delegation-first-time-managers",
    short_description: "Hand work over without losing track of it.",
    description: "Retired in favour of BWIN-LEA-320…",
    learning_outcomes: ["Delegate outcomes, not tasks"],
    requirements: [],
    target_audience: ["New managers"],
    category_id: "cat-0003",
    level: "beginner",
    language: "english",
    course_type: "typ-0002",
    delivery_mode: "dlv-0001",
    thumbnail: null,
    cover_image: null,
    promo_video_url: null,
    intro_video_url: null,
    duration_hours: 3,
    duration_minutes: 30,
    total_modules: 3,
    total_lessons: 14,
    total_quizzes: 2,
    total_assignments: 1,
    total_resources: 5,
    passing_score: 60,
    certificate_enabled: false,
    certificate_template_id: null,
    max_attempts: null,
    seat_limit: null,
    price: 79.0,
    discount_price: null,
    currency: "USD",
    enrollment_start_date: null,
    enrollment_end_date: null,
    course_start_date: null,
    course_end_date: null,
    status: "archived",
    visibility: "private",
    featured: false,
    allow_reviews: false,
    allow_discussion: false,
    sort_order: 10,
    created_by: "Amara Okafor",
    updated_by: "Amara Okafor",
    published_at: "2025-09-01 09:00:00+06",
    meta_title: null,
    meta_description: null,
    meta_keywords: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    meta_robots: "noindex, nofollow",
    created_at: "2025-08-10 09:00:00+06",
    updated_at: "2026-08-14 12:00:00+06",
    deleted_at: "2026-08-14 12:00:00+06",
    enrolled: 58,
  },
];

export const nameById = (list, id) => (list.find((x) => x.id === id) || {}).name || "—";
export const money = (v, currency) => (v == null ? "—" : `${currency === "USD" ? "$" : currency + " "}${Number(v).toFixed(2)}`);
export const durationLabel = (h, m) => [h ? `${h}h` : null, m ? `${m}m` : null].filter(Boolean).join(" ") || "—";
