// Notifications shown in Client communication > Notification (and the
// header bell dropdown, which reuses this same dataset). Mirrors the Claude
// Design source (BWIN Consultants admin panel/data/notifications.js) in
// full — `origin` distinguishes admin-created notifications from
// system-generated events. Replace with modules/notifications/services once
// the notifications API exists.
export const NOTIFICATION_ORIGINS = ["admin", "system"];

export const NOTIFICATION_ORIGIN_LABELS = { admin: "Admin created", system: "System generated" };

export const NOTIFICATION_AUDIENCES = [
  { value: "all", label: "Everyone" },
  { value: "students", label: "Students" },
  { value: "instructors", label: "Instructors" },
  { value: "clients", label: "Consultancy clients" },
  { value: "staff", label: "Internal staff" },
  { value: "custom", label: "Selected users" },
];

export const NOTIFICATION_CHANNELS = [
  { value: "in_app", label: "In-app" },
  { value: "email", label: "Email" },
  { value: "both", label: "In-app + email" },
];

export const NOTIFICATION_PRIORITIES = ["normal", "high", "urgent"];

export const NOTIFICATION_STATUSES = ["draft", "scheduled", "sent", "failed"];

export const NOTIFICATION_STATUS_LABELS = {
  draft: "Draft",
  scheduled: "Scheduled",
  sent: "Sent",
  failed: "Failed",
};

export const NOTIFICATION_STATUS_TONES = {
  draft: "neutral",
  scheduled: "info",
  sent: "success",
  failed: "error",
};

export const NOTIFICATION_CATEGORIES = ["Announcement", "Course", "Consultancy", "Automation", "Billing", "Security", "System"];

export const NOTIFICATIONS = [
  {
    id: "NT-2091",
    origin: "admin",
    title: "September cohort schedule is live",
    body:
      "<p>The September course calendar is now published. Evening cohorts run Monday and Wednesday, weekend cohorts run Saturday mornings.</p><p>If you are already enrolled, your seat carries over automatically — no action needed. Anyone who wants to switch cohorts can do it from <strong>My courses</strong> until 30 August.</p>",
    preview: "The September course calendar is now published. Evening cohorts run Monday and Wednesday…",
    category: "Course",
    audience: "students",
    channel: "both",
    priority: "normal",
    status: "sent",
    created_by: "Tobi Adeyemi",
    recipient_count: 1284,
    delivered_count: 1271,
    read_count: 903,
    click_count: 412,
    action_label: "View schedule",
    action_url: "/courses/schedule",
    scheduled_at: null,
    sent_at: "2026-08-22 08:00",
    created_at: "2026-08-21 17:22",
  },
  {
    id: "NT-2090",
    origin: "system",
    title: "Automation “Invoice reminder” failed 3 times",
    body: "Automation AU-3312 failed three consecutive runs. Last error: SMTP timeout after 30s.",
    preview: "Automation AU-3312 failed three consecutive runs. Last error: SMTP timeout after 30s.",
    category: "Automation",
    audience: "staff",
    channel: "in_app",
    priority: "urgent",
    status: "sent",
    created_by: "System",
    recipient_count: 6,
    delivered_count: 6,
    read_count: 4,
    click_count: 3,
    action_label: null,
    action_url: "/admin/automation",
    scheduled_at: null,
    sent_at: "2026-08-23 06:14",
    created_at: "2026-08-23 06:14",
  },
  {
    id: "NT-2089",
    origin: "admin",
    title: "Planned maintenance — Sunday 03:00–05:00",
    body:
      "<p>We are upgrading the automation engine this Sunday between 03:00 and 05:00 WAT. During that window, scheduled automations will queue instead of running, and the client portal may be briefly unavailable.</p><p>Nothing will be lost — queued runs start as soon as the window closes.</p>",
    preview: "We are upgrading the automation engine this Sunday between 03:00 and 05:00 WAT…",
    category: "System",
    audience: "all",
    channel: "both",
    priority: "high",
    status: "scheduled",
    created_by: "Sade Balogun",
    recipient_count: 3140,
    delivered_count: 0,
    read_count: 0,
    click_count: 0,
    action_label: null,
    action_url: null,
    scheduled_at: "2026-08-24 09:00",
    sent_at: null,
    created_at: "2026-08-22 14:05",
  },
  {
    id: "NT-2088",
    origin: "system",
    title: "14 new contact form submissions this week",
    body: "Weekly digest: 14 submissions received, 6 still unassigned.",
    preview: "Weekly digest: 14 submissions received, 6 still unassigned.",
    category: "Announcement",
    audience: "staff",
    channel: "email",
    priority: "normal",
    status: "sent",
    created_by: "System",
    recipient_count: 9,
    delivered_count: 9,
    read_count: 7,
    click_count: 5,
    action_label: null,
    action_url: "/admin/communication/contact-forms",
    scheduled_at: null,
    sent_at: "2026-08-23 07:00",
    created_at: "2026-08-23 07:00",
  },
  {
    id: "NT-2087",
    origin: "admin",
    title: "New consultancy intake form — please use it from now on",
    body:
      "<p>The old intake spreadsheet is retired. All new consultancy enquiries go through the intake form in the admin panel so scoping notes stay attached to the client record.</p><p>Priya has a five-minute walkthrough recorded if you missed the team call.</p>",
    preview: "The old intake spreadsheet is retired. All new consultancy enquiries go through the intake form…",
    category: "Consultancy",
    audience: "staff",
    channel: "in_app",
    priority: "high",
    status: "sent",
    created_by: "Priya Raman",
    recipient_count: 24,
    delivered_count: 24,
    read_count: 21,
    click_count: 14,
    action_label: "Open intake form",
    action_url: "/admin/consultancy/intake",
    scheduled_at: null,
    sent_at: "2026-08-20 09:30",
    created_at: "2026-08-20 09:12",
  },
  {
    id: "NT-2086",
    origin: "system",
    title: "Password changed for admin account",
    body: "Password for hello@bwinconsultants.com was changed from IP 102.89.34.17.",
    preview: "Password for hello@bwinconsultants.com was changed from IP 102.89.34.17.",
    category: "Security",
    audience: "staff",
    channel: "both",
    priority: "urgent",
    status: "sent",
    created_by: "System",
    recipient_count: 2,
    delivered_count: 2,
    read_count: 2,
    click_count: 1,
    action_label: null,
    action_url: "/admin/users/activity-logs",
    scheduled_at: null,
    sent_at: "2026-08-19 22:41",
    created_at: "2026-08-19 22:41",
  },
  {
    id: "NT-2085",
    origin: "admin",
    title: "Certificates for the July automation cohort are ready",
    body:
      "<p>If you completed the July business automation cohort, your certificate is in your account under <strong>Certificates</strong>. It includes a verification link your employer can check.</p>",
    preview: "If you completed the July business automation cohort, your certificate is in your account…",
    category: "Course",
    audience: "students",
    channel: "email",
    priority: "normal",
    status: "sent",
    created_by: "Tobi Adeyemi",
    recipient_count: 96,
    delivered_count: 94,
    read_count: 78,
    click_count: 61,
    action_label: "View certificate",
    action_url: "/certificates",
    scheduled_at: null,
    sent_at: "2026-08-18 11:00",
    created_at: "2026-08-18 10:41",
  },
  {
    id: "NT-2084",
    origin: "admin",
    title: "Q4 pricing update — draft, do not send yet",
    body: "<p>Placeholder for the Q4 pricing announcement. Waiting on final numbers from finance before this goes out to clients.</p>",
    preview: "Placeholder for the Q4 pricing announcement. Waiting on final numbers from finance…",
    category: "Billing",
    audience: "clients",
    channel: "both",
    priority: "normal",
    status: "draft",
    created_by: "Sade Balogun",
    recipient_count: 0,
    delivered_count: 0,
    read_count: 0,
    click_count: 0,
    action_label: null,
    action_url: null,
    scheduled_at: null,
    sent_at: null,
    created_at: "2026-08-17 16:20",
  },
  {
    id: "NT-2083",
    origin: "system",
    title: "Storage is at 82% of plan limit",
    body: "Media library is using 410 GB of the 500 GB included in your plan.",
    preview: "Media library is using 410 GB of the 500 GB included in your plan.",
    category: "System",
    audience: "staff",
    channel: "in_app",
    priority: "high",
    status: "sent",
    created_by: "System",
    recipient_count: 3,
    delivered_count: 3,
    read_count: 1,
    click_count: 0,
    action_label: null,
    action_url: "/admin/cms/media",
    scheduled_at: null,
    sent_at: "2026-08-17 05:00",
    created_at: "2026-08-17 05:00",
  },
  {
    id: "NT-2082",
    origin: "admin",
    title: "Instructor office hours move to Thursdays",
    body:
      "<p>From next week, instructor office hours run Thursdays 15:00–17:00 instead of Tuesdays. Booking links in the portal are already updated.</p>",
    preview: "From next week, instructor office hours run Thursdays 15:00–17:00 instead of Tuesdays…",
    category: "Course",
    audience: "instructors",
    channel: "in_app",
    priority: "normal",
    status: "sent",
    created_by: "Tobi Adeyemi",
    recipient_count: 31,
    delivered_count: 31,
    read_count: 27,
    click_count: 9,
    action_label: null,
    action_url: null,
    scheduled_at: null,
    sent_at: "2026-08-16 12:15",
    created_at: "2026-08-16 12:02",
  },
  {
    id: "NT-2081",
    origin: "system",
    title: "Email delivery to 2 recipients failed",
    body: "Notification NT-2085 could not be delivered to 2 recipients — mailbox full.",
    preview: "Notification NT-2085 could not be delivered to 2 recipients — mailbox full.",
    category: "System",
    audience: "staff",
    channel: "in_app",
    priority: "normal",
    status: "failed",
    created_by: "System",
    recipient_count: 2,
    delivered_count: 0,
    read_count: 0,
    click_count: 0,
    action_label: null,
    action_url: null,
    scheduled_at: null,
    sent_at: "2026-08-18 11:04",
    created_at: "2026-08-18 11:04",
  },
  {
    id: "NT-2080",
    origin: "admin",
    title: "Welcome to the new client portal",
    body:
      "<p>Your projects, automations, and training all live in one place now. Sign in with the same email you have always used — we kept your history.</p><p>If anything looks off, reply to this notification and we will sort it out.</p>",
    preview: "Your projects, automations, and training all live in one place now…",
    category: "Announcement",
    audience: "clients",
    channel: "both",
    priority: "normal",
    status: "sent",
    created_by: "Sade Balogun",
    recipient_count: 218,
    delivered_count: 214,
    read_count: 188,
    click_count: 141,
    action_label: "Open portal",
    action_url: "/portal",
    scheduled_at: null,
    sent_at: "2026-08-15 09:00",
    created_at: "2026-08-14 18:36",
  },
];
